# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161130_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='stops',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
