# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161130_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('createdBy', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('stops', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('stop_id', models.CharField(max_length=25)),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=25)),
                ('stop_latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('stop_longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('description', models.CharField(max_length=100)),
                ('photoid', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
