# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161204_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('createdBy', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('time', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('stops', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='stops',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='time',
        ),
        migrations.AlterField(
            model_name='stops',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
