# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161204_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='createdBy',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tour',
            name='distance',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
