# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161204_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='photoid',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='stop_id',
        ),
    ]
