# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20161204_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
