# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161206_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='latitude',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tour',
            name='longitude',
            field=models.IntegerField(max_length=25),
        ),
    ]
