# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20161206_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='cloud-stroll-images')),
            ],
        ),
    ]
