# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cloud-stroll-images/'),
        ),
    ]
