# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20161218_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='photo',
            field=models.ImageField(default='', upload_to='Images/'),
        ),
    ]
