# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20161221_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='Images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
