# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20161221_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(upload_to='Media/'),
        ),
    ]
