# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20161221_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stops',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
